name: Production

on:
  push:
    branches:
      - master

jobs:
  main:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 1

      - name: Login
        run: aws ecr get-login-password | docker login --username AWS --password-stdin 970312657660.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Build
        run: |
          docker build -t ejemplo-contenedor $PWD
          docker tag ejemplo-contenedor:latest 970312657660.dkr.ecr.us-east-1.amazonaws.com/ejemplo-node1:latest

      - name: Push
        run: docker push 970312657660.dkr.ecr.us-east-1.amazonaws.com/ejemplo-node1:latest

      - name: Deploy
        run: aws ecs update-service --cluster cluster-ejemplo-node-1 --service ejemplo-node1-service --task-definition first-run-task-definition --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
